# How can the company improve collaboration?

## üìñ Background
You work in the analytics department of a multinational company, and the head of HR wants your help mapping out the company's employee network using message data. 

They plan to use the network map to understand interdepartmental dynamics better and explore how the company shares information. The ultimate goal of this project is to think of ways to improve collaboration throughout the company.

## üíæ The data

The company has six months of information on inter-employee communication. For privacy reasons, only sender, receiver, and message length information are available [(source)](https://snap.stanford.edu/data/CollegeMsg.html). 

#### Messages has information on the sender, receiver, and time.
- "sender" - represents the employee id of the employee sending the message.
- "receiver" - represents the employee id of the employee receiving the message.
- "timestamp" - the date of the message.
- "message_length" - the length in words of the message.

#### Employees has information on each employee;
- "id" - represents the employee id of the employee.
- "department" - is the department within the company. 
- "location" - is the country where the employee lives.
- "age" - is the age of the employee.

_**Acknowledgments:** Pietro Panzarasa, Tore Opsahl, and Kathleen M. Carley. "Patterns and dynamics of users' behavior and interaction: Network analysis of an online community." Journal of the American Society for Information Science and Technology 60.5 (2009): 911-932._

## üí™ Competition challenge

Create a report that covers the following:  
  1. Which departments are the most/least active?
  2. Which employee has the most connections? 
  3. Identify the most influential departments and employees.
  4. Using the network analysis, in which departments would you recommend the HR team focus to boost collaboration?

## üìö LOAD PACKAGES
we will be loading all the packages which are required to our analysis

In [2]:
# Required modules

import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px

from matplotlib import pyplot as plt

In [3]:
# Config

%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 7)

## üìÅ Load the Dataframe

* messages data is present at the location data/messages.csv, the columns attributes are described above.
* employees data is present at the location data/employees.csv, the columns attributes are described above.

In [4]:
# Loading the messages dataframe

messages = pd.read_csv('data/messages.csv', parse_dates= ['timestamp'])
messages.head()

   sender  receiver           timestamp  message_length
0      79        48 2021-06-02 05:41:34              88
1      79        63 2021-06-02 05:42:15              72
2      79        58 2021-06-02 05:44:24              86
3      79        70 2021-06-02 05:49:07              26
4      79       109 2021-06-02 19:51:47              73

In [5]:
# Loading the employees dataframe

employees = pd.read_csv('data/employees.csv')
employees.head()

   id  department location  age
0   3  Operations       US   33
1   6       Sales       UK   50
2   8          IT   Brasil   54
3   9       Admin       UK   32
4  12  Operations   Brasil   51