# High fatality accidents

More information about the data can be found in the [starter notebook](notebook.ipynb)

In [1]:
# Required modules

import numpy as np
import pandas as pd
import seaborn as sns

from matplotlib import pyplot as plt

In [2]:
# Load the data

accidents = pd.read_csv('./data/accident-data.csv')
accidents.head()

,accident_index,accident_year,accident_reference,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,2020010219808,2020,10219808,-0.254001,51.462262,3,1,1,04/02/2020,3,...,6,0,9,9,1,9,9,0,0,1
1,2020010220496,2020,10220496,-0.139253,51.470327,3,1,2,27/04/2020,2,...,6,0,0,4,1,1,1,0,0,1
2,2020010228005,2020,10228005,-0.178719,51.529614,3,1,1,01/01/2020,4,...,6,0,0,0,4,1,2,0,0,1
3,2020010228006,2020,10228006,-0.001683,51.541210,2,1,1,01/01/2020,4,...,6,0,0,4,4,1,1,0,0,1
4,2020010228011,2020,10228011,-0.137592,51.515704,3,1,2,01/01/2020,4,...,5,0,0,0,4,1,1,0,0,1

In [3]:
# Inspecting the data

accidents.info()
accidents.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91199 entries, 0 to 91198
Data columns (total 27 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   accident_index                           91199 non-null  object
 1   accident_year                            91199 non-null  int64
 2   accident_reference                       91199 non-null  object
 3   longitude                                91185 non-null  float64
 4   latitude                                 91185 non-null  float64
 5   accident_severity                        91199 non-null  int64
 6   number_of_vehicles                       91199 non-null  int64
 7   number_of_casualties                     91199 non-null  int64
 8   date                                     91199 non-null  object
 9   day_of_week                              91199 non-null  int64
 10  time                                     91199 non-null  object
 11  first_road_class                         91199 non-null  int64
 12  first_road_number                        91199 non-null  int64
 13  road_type                                91199 non-null  int64
 14  speed_limit                              91199 non-null  int64
 15  junction_detail                          91199 non-null  int64
 16  junction_control                         91199 non-null  int64
 17  second_road_class                        91199 non-null  int64
 18  second_road_number                       91199 non-null  int64
 19  pedestrian_crossing_human_control        91199 non-null  int64
 20  pedestrian_crossing_physical_facilities  91199 non-null  int64
 21  light_conditions                         91199 non-null  int64
 22  weather_conditions                       91199 non-null  int64
 23  road_surface_conditions                  91199 non-null  int64
 24  special_conditions_at_site               91199 non-null  int64
 25  carriageway_hazards                      91199 non-null  int64
 26  urban_or_rural_area                      91199 non-null  int64
dtypes: float64(2), int64(21), object(4)
memory usage: 18.8+ MB

,accident_year,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,first_road_class,first_road_number,road_type,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
count,91199.0,91185.000000,91185.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,...,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000,91199.000000
mean,2020.0,-1.189258,52.351073,2.768232,1.835272,1.267382,4.121558,4.220320,790.666071,5.256001,...,5.551771,220.231987,0.352975,1.185309,2.065308,1.702047,1.391583,0.244740,0.180594,1.323205
std,0.0,1.367786,1.327573,0.456682,0.677272,0.681473,1.932200,1.443475,1580.817743,1.684878,...,1.015113,913.692832,1.698116,2.445924,1.747690,1.845786,0.925690,1.318554,1.149791,0.468031
min,2020.0,-7.497375,49.970479,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000
25%,2020.0,-2.107789,51.457237,3.000000,1.000000,1.000000,2.000000,3.000000,0.000000,6.000000,...,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
50%,2020.0,-1.046912,51.763385,3.000000,2.000000,1.000000,4.000000,4.000000,34.000000,6.000000,...,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,2020.0,-0.125238,53.297386,3.000000,2.000000,1.000000,6.000000,6.000000,538.000000,6.000000,...,6.000000,0.000000,0.000000,0.000000,4.000000,1.000000,2.000000,0.000000,0.000000,2.000000
max,2020.0,1.756257,60.541144,3.000000,13.000000,41.000000,7.000000,6.000000,9174.000000,9.000000,...,6.000000,9174.000000,9.000000,9.000000,7.000000,9.000000,9.000000,9.000000,9.000000,3.000000